### PR TITLE
Visualizer getting slow with big number of poses

### PR DESCRIPTION
**Pull request by RoniEmad**
When using the visualizer, I found that the pipeline FPS is getting slower as the number of frames increases.

It starts with 25FPS and by the time it goes under 2FPS.

The issue is in **_o3d.geometry.TriangleMesh.create_sphere()_** which is not efficient, so the visualization gets slower as the number of spheres(trajectory poses) increases.

https://github.com/PRBonn/kiss-icp/blob/d848ab891ea6684d41401cc000a6e98eb7f7a3a0/src/python/kiss_icp/tools/visualizer.py#L224-L232

Using rosbags, it takes too long to process a bag when viewing the trajectory.

I am working on a ROS wrapper, this was causing a problem that when the delay increases the pipeline starts to miss messages and the odometry gets crazy.

Using **_o3d.geometry.PointCloud()_** instead solved the issue.
However there a small issue is that all pointclouds in the same open3d window must have the same point size using **_viz.update_geometry()_**.

### CODE REVIEW

**Comment by nachovizzo** [comment]
@RoniEmad Have you tried disabling the trajectory? You can just press `T` on the keyboard and this should solve the problem.

The trajectory path is not Ideal at all, but should only used for debugging

**Comment by RoniEmad** [comment]
Yes, it works well when I press T.
But in case I need to see the trajectory path for debugging in real-time, I can't because of the delay.

**Comment by nachovizzo** [comment]
I see, I guess this won't be a big problem once the ROS wrapper is ou there. I'll skip integrating this since it's suboptimal the problem of the point size, the trajectory in the visualizer is a nice to have feature...but it's to complicated to implement properly on my humble opinion


I'll keep this in mind when using rviz ;) there is much easier to debug this type of scenarios

**Comment by RoniEmad** [comment]
Great, Thank you for your reply :)

**Pull request closed without merging**
