### PR TITLE
Add ROS2 support

### PR DESCRIPTION
**Pull request by shrijitsingh99**
I tested on some bag files I had and everything seemed to work. 
There is one issue where it `ros2` command is not able to the `kiss_icp` package but if I run the binaries directly it works. THis may be an issue with my PC only.

### CODE REVIEW

**Comment by nachovizzo** [comment]
Hello @shrijitsingh99 thanks for opening a PR! Just out of curiosity, have you checked this fork: https://github.com/HIPERT-SRL/kiss-icp? It looks like they went a bit deeper and also provided launch files in python, etc. 

Would you mind trying to take inspiration from that branch? It looks like this PR is more like a "draft". What do you think? 

Thanks again!

**Comment by shrijitsingh99** [comment]
@nachovizzo I wasn't aware of that repo when I worked on this. Both implementations are pretty similar, though one difference is that I inherited from the `Node` class for `OdometeryServer`, this allows for composing the node if needed.

Sorry, about putting an incomplete PR. I had added some launch file locally but never got to pushing them.
I added everything now, so this PR should be ready after some testing.

**Comment by nachovizzo** [comment]
> @nachovizzo I wasn't aware of that repo when I worked on this. Both implementations are pretty similar, though one difference is that I inherited from the `Node` class for `OdometeryServer`, this allows for composing the node if needed.
> 
> Sorry, about putting an incomplete PR. I had added some launch file locally but never got to pushing them. I added everything now, so this PR should be ready after some testing.

Please! No need to say sorry!!! Thanks for contributing!

I'm now integrating these changes into our local dev pipeline. I will need to make some changes, if you can give me write permissions to your branch I can directly push there. If not, I can fork your fork, so your contribution is still clear.

**Comment by nachovizzo** [comment]
Update: started to work on nacho/tweak_ros2_node

**Pull request closed without merging**
